apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataset-query-listing.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "dataset-query-listing.name" . }}